"""Initial migration

Revision ID: 0a834168f9c4
Revises: 
Create Date: 2021-03-13 16:31:44.883838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a834168f9c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('amount', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('image_source', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
